apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: garm
  name: garm
  namespace: kube-public
  selfLink: /apis/extensions/v1beta1/namespaces/kube-public/deployments/garm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: garm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: garm
    spec:
      containers:
      - env:
        - name: athenz_domain
          valueFrom:
            configMapKeyRef:
              key: athenz-domain
              name: garm-extapi
        - name: service_name
          valueFrom:
            configMapKeyRef:
              key: service-name
              name: garm-extapi
        - name: key
          valueFrom:
            configMapKeyRef:
              key: server-key
              name: garm-extapi
        - name: cert
          valueFrom:
            configMapKeyRef:
              key: server-cert
              name: garm-extapi
        - name: ca
          valueFrom:
            configMapKeyRef:
              key: ca-public-key
              name: garm-extapi
        - name: root_ca
          valueFrom:
            configMapKeyRef:
              key: athenz-root-ca
              name: garm-extapi
        - name: athenz_private_key
          valueFrom:
            configMapKeyRef:
              key: athenz-private-key
              name: garm-extapi
        image: yahoojapan/garm:latest
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 3
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 2
          periodSeconds: 3
        name: garm
        ports:
        - containerPort: 443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/garm/
          name: garm-config
        - mountPath: /etc/garm/ssl
          name: cert
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: garm-config
        name: garm-config
      - name: cert
        secret:
          defaultMode: 420
          secretName: garm-secret-ca
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-06-29T05:23:57Z
    lastUpdateTime: 2018-06-29T05:23:57Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-06-29T05:23:55Z
    lastUpdateTime: 2018-06-29T05:23:57Z
    message: ReplicaSet "garm-57757bcf99" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
